<?php

$dictionary['Account']['fields']['billing_id'] = array(
    'name' => 'billing_id',
    'vname' => 'LBL_BILLING_ID',
    'type' => 'varchar',
    'len' => '150',
    'comment' => 'Billing Id generated by Simple Billing System',
    'merge_filter' => 'disabled',
    'audited' => false,
    'studio' => false,
);